### ISSUE TITLE
package-lock.json broken

### ISSUE THREAD

**Issue by SchoolGuy** [jitsi/moderated-meetings#19]
Currently eslint-config-jitsi references a commit which was deleted.

@saghul deleted the 1.0.3 branch a few weeks back which contained: `f292fbc07689eb3dbeb81c074accff25b448b074`

But we actually have in master `b84485e1c214162c089f7df09c15cde62f24640d`

This was done via PR https://github.com/jitsi/eslint-config-jitsi/pull/14

**Comment by saghul** [comment]
Ops. We should update the dependency to the latest eslint-config version.

**Comment by SchoolGuy** [comment]
I think this issue is no longer valid. Closing as such.
